service: bonzai-api
frameworkVersion: '4'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-north-1
  stage: dev
  environment:
    TABLE_NAME: Bonzai
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
  httpApi:
    cors:
      allowedOrigins: ['*']
      allowedHeaders: ['Content-Type','Authorization']
      allowedMethods: ['GET','POST','PATCH','DELETE','OPTIONS']

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Query
          Resource:
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/Bonzai
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/Bonzai/index/GSI1

functions:
  listRooms:
    handler: src/handlers/rooms/listRooms.handler
    events:
      - httpApi:
          method: GET
          path: /rooms

  listBookings:
    handler: src/handlers/bookings/listBookings.handler
    events:
      - httpApi:
          method: GET
          path: /bookings

resources:
  Resources:
    BonzaiTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Bonzai
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
          - AttributeName: GSI1PK
            AttributeType: S
          - AttributeName: GSI1SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: GSI1
            KeySchema:
              - AttributeName: GSI1PK
                KeyType: HASH
              - AttributeName: GSI1SK
                KeyType: RANGE
            Projection:
              ProjectionType: ALL